apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      containers:
      - name: e-commerce
        image: anurudhan/e-commerce:latest  
        ports:
        - containerPort: 3000 
