apiVersion: v1
kind: Service
metadata:
  name: e-commerce-service
spec:
  type: NodePort 
  selector:
    app: e-commerce
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000
      nodePort: 30007  
